apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio-registry-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akashmate/krakend-java-code-repo.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: krakend-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
