apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: krk-application-namespace
  labels:
    app: keycloak
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: harbor.massiltech.com/krakendproject/keycloak:26.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ["/opt/keycloak/bin/kc.sh"]
        args: ["start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"]
        env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        - name: KEYCLOAK_FRONTEND_URL
          value: "http://10.175.1.110:31438/admin"
        - name: KEYCLOAK_PROXY
          value: "edge"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://10.175.1.110:31304/postgres?user=postgres&password=69NNHvnsyC"
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
        - name: template-ftl
          mountPath: /opt/keycloak/themes/custom/login/template.ftl
          subPath: template.ftl
        - name: theme-file
          mountPath: /opt/keycloak/themes/custom/login/theme.properties
          subPath: theme.properties
        - name: logincss-file
          mountPath: /opt/keycloak/themes/custom/login/resources/css/login.css
          subPath: login.css
        - name: massillogo-file
          mountPath: /opt/keycloak/themes/custom/login/resources/img/massil-logo.svg
          subPath: massil-logo.svg
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
      - name: template-ftl
        configMap:
          name: massil-template
      - name: theme-file
        configMap:
          name: theme-properties-config
      - name: massillogo-file
        configMap:
          name: massil-logo-config
      - name: logincss-file
        configMap:
          name: login-css-config
