apiVersion: apps/v1
kind: Deployment
metadata:
  name: massilgateway-dep-file
  namespace: krk-application-namespace
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: massilgateway
  template:
    metadata:
      labels:
        app: massilgateway
    spec:
      containers:
        - name: massilgateway
          image: harbor.massiltech.com/krakendproject/rupesh2811/massilgateway2.0:1.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/app/config/application.yml"
            - name: DOCKER_HOST
              value: "tcp://host.docker.internal:2375"
          volumeMounts:
            - name: config-map
              mountPath: /app/config/application.yml
              subPath: application.yml
      volumes:
        - name: config-map
          hostPath:
            path: /home/masssil/Documents/application.yml
            type: File
