apiVersion: apps/v1
kind: Deployment
metadata:
  name: massilgateway-dep-file
  namespace: krk-application-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: massilgateway
  template:
    metadata:
      labels:
        app: massilgateway
    spec:
      containers:
        - name: massilgateway
          image: harbor.massiltech.com/krakendproject/rupesh2811/massilgateway4.0:29.0
          ports:
            - containerPort: 8082
          env:
            - name: DOCKER_HOST
              value: "tcp://10.175.1.110:2375"
