apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  namespace: krk-application-namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/keycloak-data # Replace with a valid path on your node
